# Frontend/Dockerfile
FROM node:22-alpine
WORKDIR /app

# 1️⃣ Copy only files needed to install dependencies and generate Prisma client
COPY package*.json ./

# 2️⃣ Install dependencies
RUN npm install

# 4️⃣ Copy the rest of the application source
COPY . .

# 5️⃣ Expose and run app
EXPOSE 5173
CMD ["npm", "run", "dev"]
