version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    container_name: expense-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: expense-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
