version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: expense-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    container_name: expense-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
